# Default values for fis.

replicaCount: 2
logLevel: info
host: #0.0.0.0
backend: #http://backend-fis:9898/echo
backends: []

image:
  repository: feelguuds/financial-integration-service
  tag: latest
  pullPolicy: Always

ui:
  color: "#34577c"
  message: ""
  logo: ""

# failure conditions
faults:
  delay: false
  error: false
  unhealthy: false
  unready: false
  testFail: false
  testTimeout: false

database:
  host: simfiny-db-cluster-do-user-11446161-0.b.db.ondigitalocean.com
  port: 25060
  user: doadmin
  password: AVNS_QIibiEIbI5JVODo
  name: financial-integration-service-db
  sslMode: require
  max_connection_attempts: 4
  max_connection_retries: 4
  max_connection_retry_timeout: 500ms
  max_connection_retry_sleep_interval: 100ms

plaid:
  enabled: true
  client_id: 61eb5d49ea3b4700127560d1
  secret_key: 465686056e8fd1b87db3d993d096d8
  env: sandbox
  webhook_url: ""
  # Only required for OAuth:
  # For sandbox, set PLAID_REDIRECT_URI to 'http://localhost:3000/'
  # The OAuth redirect flow requires an endpoint on the developer's website
  # that the bank website should redirect to. You will need to configure
  # this redirect URI for your client ID through the Plaid developer dashboard
  # at https://dashboard.plaid.com/team/api.
  # For development or production, you will need to use an https:// url
  # If you are not set up to use localhost with https:// on your system, you will be unable to test OAuth in development or production.
  # In this case you can leave the PLAID_REDIRECT_URI blank.
  redirect_url: ""
  # Only institutions that support ALL listed products will be displayed in Link.
  # If you don't see the institution you want in Link, remove any products you aren't using.
  # Important: When moving to Production, make sure to update this list with only the products
  # you plan to use. Otherwise, you may be billed for unneeded products.
  products: transactions,auth,identity,assets,investments,liabilities

newRelic:
  enabled: true
  key: 62fd721c712d5863a4e75b8f547b7c1ea884NRAL

# Kubernetes Service settings
service:
  enabled: true
  # environment can either take values: local, dev, staging, prod
  environment: prod
  annotations: {}
  type: ClusterIP
  metricsPort: 9797
  httpPort: 9898
  externalPort: 9898
  grpcPort: 9896
  grpcService: financial-integration-service
  nodePort: 31198
  # the port used to bind the http port to the host
  # NOTE: requires privileged container with NET_BIND_SERVICE capability -- this is useful for testing
  # in local clusters such as kind without port forwarding
  hostPort:
  env: "dev"

# enable h2c protocol (non-TLS version of HTTP/2)
h2c:
  enabled: false

# enable tls on the fis service
tls:
  enabled: false
  # the name of the secret used to mount the certificate key pair
  secretName:
  # the path where the certificate key pair will be mounted
  certPath: /data/cert
  # the port used to host the tls endpoint on the service
  port: 9899
  # the port used to bind the tls port to the host
  # NOTE: requires privileged container with NET_BIND_SERVICE capability -- this is useful for testing
  # in local clusters such as kind without port forwarding
  hostPort:

# create a certificate manager certificate (cert-manager required)
certificate:
  create: false
  # the issuer used to issue the certificate
  issuerRef:
    kind: ClusterIssuer
    name: self-signed
  # the hostname / subject alternative names for the certificate
  dnsNames:
    - financial-integration-service

# metrics-server add-on required
hpa:
  enabled: false
  maxReplicas: 10
  # average total CPU usage per pod (1-100)
  cpu:
  # average memory usage per pod (100Mi-1Gi)
  memory:
  # average http requests per second per pod (k8s-prometheus-adapter)
  requests:

# Redis address in the format <host>:<port>
cache: ""
# Redis deployment
redis:
  enabled: false
  repository: redis
  tag: 6.0.8

postgresLocalDB:
  enabled: false

serviceAccount:
  # Specifies whether a service account should be created
  enabled: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

# set container security context
securityContext: {}

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: financial-integration-service.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

linkerd:
  profile:
    enabled: false

# create Prometheus Operator monitor
serviceMonitor:
  enabled: false
  interval: 15s
  additionalLabels: {}

resources:
  limits:
  requests:
    cpu: 1m
    memory: 16Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

integrationTests:
  enabled: false
