builds:
  - main: ./cmd/podinfo
    binary: main
    ldflags: -s -w -X github.com/SimifiniiCTO/simfiny-financial-integration-service/pkg/version.REVISION={{.Commit}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
  - main: ./cmd/podcli
    binary: main
    ldflags: -s -w -X github.com/SimifiniiCTO/simfiny-financial-integration-service/pkg/version.REVISION={{.Commit}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*
