version: '3.7'

services:
  service_instance:
    tty: true # Makes color output work nicely.
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    working_dir: /build
    container_name: service_instance
    ports:
      - "9896:9896" # grpc port
    restart: always
    environment:
      - air_wd=/build
    networks:
      - user-network
    volumes:
      - '.:/go/src/github.com/SimifiniiCTO/simfiny-financial-integration-service'
      - goData:/go/pkg/mod
      - ./:/build
    env_file:
      - ./service.env
    depends_on:
      - service_db
    command:
      - bash
      - -c
      - /build/compose/api-entrypoint.sh

  service_db:
    container_name: service_db
    image: postgres
    environment:
      POSTGRES_DB: service_db
      POSTGRES_USER: service_db
      POSTGRES_PASSWORD: service_db
      PGDATA: /data/service_db
    volumes:
      - service_db:/data/service_db
    ports:
      - "5433:5432"
    restart: always
    networks:
      - user-network

networks:
  user-network:
    driver: bridge

volumes:
  service_db:
  tmpData:
  goData: