FROM golang:1.19.4

ARG BUILD_DATE
ARG VERSION
ARG REVISION

# define container level tags
LABEL version="1.0" maintainer="Yoan Yomba <yoanyombapro@gmail.com>"
LABEL author="Yoan Yomba"
LABEL company="simfinii"
LABEL maintainer="simfinii" \
  org.opencontainers.image.created=$BUILD_DATE \
  org.opencontainers.image.url="https://github.com/SimifiniiCTO/simfiny-financial-integration-service" \
  org.opencontainers.image.source="https://github.com/SimifiniiCTO/simfiny-financial-integration-service" \
  org.opencontainers.image.version=$VERSION \
  org.opencontainers.image.revision=$REVISION \
  org.opencontainers.image.vendor="simfinii" \
  org.opencontainers.image.title="simfinii" \
  org.opencontainers.image.description="Microservice For The Simifinii \
  Platform" \
  org.opencontainers.image.licenses="MIT"

# It is important that these ARG's are defined after the FROM statement
ARG ACCESS_TOKEN_USR="yoanyombapro1234"
ARG ACCESS_TOKEN_PWD="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"

# Create the user and group files that will be used in the running 
# container to run the process as an unprivileged user.
RUN mkdir /user && \
  echo 'nobody:x:65534:65534:nobody:/:' > /user/passwd && \
  echo 'nobody:x:65534:' > /user/group
# Create a netrc file using the credentials specified using --build-arg
RUN printf "machine github.com\n\
  login ${ACCESS_TOKEN_USR}\n\
  password ${ACCESS_TOKEN_PWD}\n\
  \n\
  machine api.github.com\n\
  login ${ACCESS_TOKEN_USR}\n\
  password ${ACCESS_TOKEN_PWD}\n"\
  >> /root/.netrc
RUN chmod 600 /root/.netrc

RUN git config --global url."https://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:x-oauth-basic@github.com/SimifiniiCTO".insteadOf "https://github.com/SimifiniiCTO"

# create a directory in which to copy files on local filesystem
RUN mkdir -p /go/src/github.com/SimifiniiCTO/simfiny-financial-integration-service

# copy files on local file system
ADD . /build

# define execution context
WORKDIR /build

# define container entrypoint
ENTRYPOINT bash -c /build/compose/api-entrypoint.sh