package main

import (
	"gorm.io/gen"

	proto "github.com/SimifiniiCTO/simfiny-financial-integration-service/internal/generated/api/v1"
)

// Querier is the interface of added queries that the various
// types should implement
type Querier interface {
	// SELECT * FROM @@table
	//  {{where}}
	//      user_id=@user_id
	//  {{end}}
	GetByUserID(user_id int) (gen.T, error) // returns struct and error
	// SELECT * FROM @@table
	//  {{where}}
	//      id=@id
	//  {{end}}
	GetByID(id int) (gen.T, error) // returns struct and error
	// SELECT * FROM @@table
	//  {{where}}
	//      id IN (@ids)
	//  {{end}}
	GetByIDs(ids []int) ([]gen.T, error) // returns slice of struct and error
}

func main() {
	AutoGenerateDAL()
}

// Autogenerate data access layer for all models
func AutoGenerateDAL() {
	g := gen.NewGenerator(gen.Config{
		OutPath:           "../../internal/generated/dal",
		WithUnitTest:      true,
		FieldNullable:     true,
		FieldCoverable:    true,
		FieldSignable:     false,
		FieldWithIndexTag: true,
		FieldWithTypeTag:  true,
		Mode:              gen.WithoutContext | gen.WithDefaultQuery | gen.WithQueryInterface, // generate mode
	})

	var models = proto.GetDatabaseSchemas()
	models = append(models, proto.GetClickhouseSchemas()...)

	// generate from struct in project
	g.ApplyBasic(models...)

	// Generate Type Safe API with Dynamic SQL defined on Querier interface for `model.User` and `model.Company`
	g.ApplyInterface(func(Querier) {}, models...)

	g.Execute()
}
