CREATE TABLE IF NOT EXISTS TransactionInternal (
    AccountId                       LowCardinality(String),
    AccountOwner                    LowCardinality(String),
    Amount                          Float64,
    AuthorizedDate                  LowCardinality(String),
    AuthorizedDatetime              LowCardinality(String),
    CategoryId                      LowCardinality(String),
    CheckNumber                     LowCardinality(String),
    CurrentDate                     LowCardinality(String),
    CurrentDatetime                 LowCardinality(String),
    ID                              String DEFAULT generateUUIDv4(),
    IsoCurrencyCode                 LowCardinality(String),
    LinkId                          UInt64,
    LocationAddress                 LowCardinality(String),
    LocationCity                    LowCardinality(String),
    LocationCountry                 LowCardinality(String),
    LocationLat                     Float64,
    LocationLon                     Float64,
    LocationPostalCode              LowCardinality(String),
    LocationRegion                  LowCardinality(String),
    LocationStoreNumber             LowCardinality(String),
    MerchantName                    LowCardinality(String),
    Name                            LowCardinality(String),
    PaymentChannel                  LowCardinality(String),
    PaymentMetaByOrderOf            LowCardinality(String),
    PaymentMetaPayee                LowCardinality(String),
    PaymentMetaPayer                LowCardinality(String),
    PaymentMetaPaymentMethod        LowCardinality(String),
    PaymentMetaPaymentProcessor     LowCardinality(String),
    PaymentMetaPpdId                LowCardinality(String),
    PaymentMetaReason               LowCardinality(String),
    PaymentMetaReferenceNumber      LowCardinality(String),
    Pending                         Bool,
    PendingTransactionId            LowCardinality(String),
    PersonalFinanceCategoryDetailed LowCardinality(String),
    PersonalFinanceCategoryPrimary  LowCardinality(String),
    Sign                            Int8,
    Time                            DateTime,
    TransactionCode                 LowCardinality(String),
    TransactionId                   LowCardinality(String),
    UnofficialCurrencyCode          LowCardinality(String),
    UserId                          UInt64,
    Categories                      Array(String)
) ENGINE = CollapsingMergeTree(Sign)
PARTITION BY toYYYYMM(Time)
ORDER BY (Time, ID)
PRIMARY KEY (Time, ID);
