version: '3.7'

services:
  service:
    build:
      context: "../"
      dockerfile: Dockerfile.dev
    container_name: service
    ports:
      - "9896:9896" # grpc port
    restart: always
    environment:
      - newrelic-api-key=3000
    networks:
      - service-network
    volumes:
      - '..:/go/src/github.com/SimifiniiCTO/simfiny-financial-integration-service'
    env_file:
      - ../financial-integration-service.env
    depends_on:
      - service-db

  service-db:
    image: postgres:latest
    container_name: service-db
    ports:
      - "6000:5432"
    environment:
      - POSTGRES_PASSWORD=service-db
      - POSTGRES_USER=service-db
      - POSTGRES_DB=service-db
      - PGDATA=/data/service-db
    volumes:
      - service-db:/data/service-db
    networks:
      - service-network

networks:
  service-network:
    driver: bridge

volumes:
  service-db: {}
  tmpData:
  goData: