version: '3'
services:
  ngrok:
    image: ngrok/ngrok:alpine
    environment:
      - NGROK_AUTHTOKEN=2JwfMUzmEbQBW2iH599MuX9bAeq_6MqUZtf6kCEkcjPci7SH9
    command: http service:9896
    ports:
      - 4040:4040
    networks:
      - service-network

networks:
  service-network:
    driver: bridge