package plaidhandler

import (
	"time"

	"github.com/plaid/plaid-go/v12/plaid"
)

// The ItemToken type contains an access token and the item ID associated with it.
// @property {string} AccessToken - The access token associated with the Item data being requested for.
// An access token is a credential used to access protected resources on behalf of an entity (user,
// application, etc.).
// @property {string} ItemId - ItemId is a string property that represents the unique identifier of an
// item associated with an access token.
type ItemToken struct {
	// The access token associated with the Item data is being requested for.
	AccessToken string
	// The `item_id` value of the Item associated with the returned `access_token`
	ItemId string
}

// NewItemTokenFromPlaid creates a new ItemToken from a plaid.ItemPublicTokenExchangeResponse
func NewItemTokenFromPlaid(input plaid.ItemPublicTokenExchangeResponse) (ItemToken, error) {
	return ItemToken{
		AccessToken: input.GetAccessToken(),
		ItemId:      input.GetItemId(),
	}, nil
}

// The LinkTokenOptions type contains various options for creating a Link token in Go, including client
// user ID, legal name, phone number, email address, and update mode.
// @property {string} ClientUserID - ClientUserID is a string property that represents the unique
// identifier of the user in your application. This property is used to associate the user's Link token
// with their account in your system.
// @property {string} LegalName - LegalName is a string property that represents the legal name of the
// user associated with the Link token.
// @property PhoneNumber - PhoneNumber is a pointer to a string that represents the user's phone
// number. It is an optional field in the LinkTokenOptions struct. If provided, it will be used to
// pre-fill the phone number field in the Link flow.
// @property PhoneNumberVerifiedTime - `PhoneNumberVerifiedTime` is a pointer to a `time.Time` value
// that represents the date and time when the user's phone number was verified. If the phone number has
// not been verified, this field will be nil.
// @property {string} EmailAddress - EmailAddress is a string property that represents the email
// address of the user associated with the Link token.
// @property EmailAddressVerifiedTime - EmailAddressVerifiedTime is a property of the LinkTokenOptions
// struct that represents the time when the user's email address was last verified. It is of type
// *time.Time, which means it can either be a valid time.Time value or a nil pointer. If the email
// address has never been verified, the
// @property {bool} UpdateMode - UpdateMode is a boolean property that indicates whether the Link token
// being created is for updating an existing user's information or creating a new user. If UpdateMode
// is set to true, the Link token will be used to update the user's information. If it is set to false,
// the Link token will
type LinkTokenOptions struct {
	ClientUserID             string
	LegalName                string
	PhoneNumber              *string
	PhoneNumberVerifiedTime  *time.Time
	EmailAddress             string
	EmailAddressVerifiedTime *time.Time
	UpdateMode               bool
}

// The LinkToken interface defines methods for retrieving a token string and its expiration time.
// @property {string} Token - The Token method returns a string that represents a unique identifier or
// access token for a particular resource or service.
// @property Expiration - `Expiration` is a method that returns the time when the link token will
// expire. It is likely that the link token is used for authentication or authorization purposes, and
// it is important to know when it will no longer be valid. The method returns a `time.Time` value
// representing the expiration time.
type LinkToken interface {
	Token() string
	Expiration() time.Time
}

var (
	_ LinkToken = &PlaidLinkToken{}
)

// The PlaidLinkToken type contains a link token string and an expiration time.
// @property {string} LinkToken - LinkToken is a string that represents a unique token generated by the
// Plaid API that is used to initiate a Plaid Link session. This token is passed to the client-side
// application and used to authenticate the user and connect their bank account to the Plaid API.
// @property Expires - `Expires` is a property of the `PlaidLinkToken` struct that represents the
// expiration time of the Plaid Link token. It is of type `time.Time`, which is a built-in Go type that
// represents a point in time. The `Expires` property indicates the date and time when
type PlaidLinkToken struct {
	LinkToken string
	Expires   time.Time
}

// Token returns the link token string
func (p *PlaidLinkToken) Token() string {
	return p.LinkToken
}

// Expiration returns the expiration time of the link token
func (p *PlaidLinkToken) Expiration() time.Time {
	return p.Expires
}
