{ { - if .Values.autoscaling.enabled - } }
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: { { template "fis.fullname" . } }
  labels:
    { { - include "fis.labels" . | nindent 4 } }
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: { { template "fis.fullname" . } }
  minReplicas: { { .Values.autoscaling.minReplicas } }
  maxReplicas: { { .Values.autoscaling.maxReplicas } }
  metrics:
  { { - if .Values.autoscaling.cpu } }
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: { { .Values.autoscaling.cpu } }
  { { - end } }
  { { - if .Values.autoscaling.memory } }
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: { { .Values.autoscaling.memory } }
  { { - end } }
  { { - if .Values.autoscaling.requests } }
  - type: Pods
    pods:
      metric:
        name: http_requests
      target:
        type: AverageValue
        averageValue: { { .Values.autoscaling.requests } }
  { { - end } }
  { { - end } }