{ { - if .Values.service.enabled - } }
apiVersion: v1
kind: Service
metadata:
  name: { { template "fis.fullname" . } }
  labels:
    { { - include "fis.labels" . | nindent 4 } }
  { { - with .Values.service.annotations } }
annotations:
  { { toYaml . | indent 4 } }
  { { - end } }
spec:
  type: { { .Values.service.type } }
  ports:
    { { - if .Values.service.grpcPort } }
    - port: { { .Values.service.grpcPort } }
      targetPort: grpc
      protocol: TCP
      name: grpc
    { { - end } }
  selector:
    { { - include "fis.selectorLabels" . | nindent 4 } }
  { { - end } }
