{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fis.serviceAccountName" . }}
  labels:
    {{- include "fis.labels" . | nindent 4 }}
{{- end -}}
