name: release-chart
on: [push, pull_request]

jobs:
  release-chart:
    env:
      GCR_IMAGE: ghcr.io/${{ github.repository_owner }}/financial-integration-service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sigstore/cosign-installer@v3
      - uses: fluxcd/flux2/action@main
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare
        id: prep
        run: |
          VERSION=sha-${GITHUB_SHA::8}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF/refs\/tags\//}
          fi
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "REVISION=${GITHUB_SHA}" >> $GITHUB_OUTPUT
      - name: Generate images meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/feelguuds/financial-integration-service
            ghcr.io/simfiniicto/financial-integration-service
          tags: |
            type=raw,value=${{ steps.prep.outputs.VERSION }}
            type=raw,value=latest
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts
          charts_url: https://charts.melodiy.io
          owner: SimifiniiCTO
          repository: simfiny-financial-integration-service
          branch: gh-pages
      - name: Sample Publish
        run: |
          helm chart save ${{ github.workspace }}/charts/financial-integration-service ${{ github.workspace }}/charts/financial-integration-service-${{ steps.prep.outputs.VERSION }}.tgz
          helm chart push ${{ env.GCR_IMAGE }}:${{ github.sha }}
      - name: Publish Helm chart to GHCR
        run: |
          helm package charts/financial-integration-service
          helm push financial-integration-service-${{ steps.prep.outputs.VERSION }}.tgz oci://ghcr.io/simifiniicto/charts
          rm financial-integration-service-${{ steps.prep.outputs.VERSION }}.tgz
      - name: Publish Helm chart to GHCR
        run: |
          helm package charts/financial-integration-service
          helm push financial-integration-service-${{ steps.prep.outputs.VERSION }}.tgz oci://ghcr.io/stefanprodan/charts
          rm financial-integration-service-${{ steps.prep.outputs.VERSION }}.tgz
      - name: Publish Flux OCI artifact to GHCR
        run: |
          flux push artifact oci://ghcr.io/stefanprodan/manifests/financial-integration-service:${{ steps.prep.outputs.VERSION }} \
            --path="./kustomize" \
            --source="${{ github.event.repository.html_url }}" \
            --revision="${GITHUB_REF_NAME}/${GITHUB_SHA}"
          flux tag artifact oci://ghcr.io/stefanprodan/manifests/financial-integration-service:${{ steps.prep.outputs.VERSION }} --tag latest