name: release-chart
on: [push, pull_request]

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts
          charts_url: https://charts.melodiy.io
          owner: SimifiniiCTO
          repository: simfiny-financial-integration-service
          branch: gh-pages